name: MY Build lpud
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      ksu_fork:
        required: true
        type: string
      pack_lkm:
        required: false
        type: boolean
        default: true
      use_cache:
        required: false
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download linuxxpu with patched dir
      uses: actions/download-artifact@main
      with:
        name: linuxxpu
        path: .
        github-token: ${{ env.GITHUB_TOKEN }}
        
    - name: Setup Rust
      run: |
        rustup update stable
        rustup target add aarch64-linux-android

    - name: Cache lpud
      if: ${{ inputs.ksu_fork == 'SUKISU' }} || ${{ inputs.ksu_fork == 'xxKSU' }}
      uses: Swatinem/rust-cache@master
      with:
        workspaces: userspace/lpud
        cache-targets: false

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r29
        
    - name: Build lpud
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          export KSU_PACKAGE_NAME="com.ahmad.linuxxpu.pr"
        fi
        source .github/scripts/setup-rust-build.sh ${{ inputs.target }} 26
        cargo build --target $TRIPLE --release --manifest-path ./userspace/lpud/Cargo.toml

    - name: Upload ksud artifact
      if: ${{ inputs.ksu_fork == 'SUKISU' }} || ${{ inputs.ksu_fork == 'xxKSU' }}
      uses: actions/upload-artifact@main
      with:
        name: lpud-${{ inputs.target }}
        path: target/${{ inputs.target }}/release/lpud*
